### DISCUSSION TITLE
Dedented multiline string

### DISCUSSION THREAD

**Discussion by twavv** [kdl-org/kdl#173] [Q&A] [answered]
Hi hi hello hi!

I'm considering using KDL in one of my projects as an alternative to YAML for a document-based syntax. One thing that I'm missing is seamless multiline string support. For example, in YAML, one can use the pipe-string syntax:

```yaml
some:
  deeply:
    nested:
      value: |
        I am a string
        that includes multiple lines
        and is dedented in the parsed output
```

I'm wondering if there are any plans for a similar syntax in KDL. For context, I'm hoping to be able to embed markdown text relatively easily. I see the `r#"..."` syntax but it's a touch ugly and doesn't solve the dedent issue.

EDIT: I understand if this isn't a design goal of KDL, but I haven't seen it discussed (hence this discussion).
